name: Daily Positive Emails

on:
  schedule:
    # Runs at 15:00 UTC every day (adjust time as needed)
    - cron: '0 15 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-emails:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mistralai gspread google-auth python-dotenv

    - name: Decode and use Google service key
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_KEY }}" | base64 -d > sinuous-canto-427508-k5-8fe207f9654f.json

    - name: Create .env file
      run: |
        echo "EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}" > .env
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
        echo "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}" >> .env

    - name: Run email script
      run: python sheets.py 